### ISSUE TITLE
Necessário tela de login e definição de permissões para usuários?

### ISSUE THREAD

**Issue by maffalcao** [Tecnofit/Desafio-Tecnofit#34]
No texto do escopo, vejo dois perfis aqui bem distintos: administradores (aqueles que cadastram alunos, exercícios e treinos) e alunos (que visualizam apenas seus dados, treinos e, no treino ativo, possuem a ação de marcar o exercício como finalizado ou pular o mesmo).

Nesse sentido, me parece necessário a criação de usuários, como cadastro de senhas e definição de qual perfil pertence. Assim, em função do perfil identificado no login, será possível determinar as ações a serem executadas.

**Comment by whera** [comment]
Olá @maffalcao, tudo bem? 
Toda a parte de autenticação e autorização fica a critério do candidato desenvolver ou não. Se o mesmo optar por desenvolver será considerado um diferencial e o código será avaliado com os mesmos critérios do resto do desafio
